# Generated by Django 2.0 on 2018-11-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_account_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
