# Generated by Django 2.0 on 2018-10-24 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_readnumdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
