# Generated by Django 2.0 on 2018-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20181103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='当前类型主键'),
        ),
    ]
