# Generated by Django 2.0 on 2018-11-15 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentCity', models.CharField(max_length=10)),
                ('pm25', models.CharField(max_length=10)),
                ('data', models.DateField(verbose_name=django.utils.timezone.now)),
                ('Picture', models.ImageField(upload_to='')),
                ('the_weather', models.TextField()),
            ],
        ),
    ]
