# Generated by Django 2.0 on 2018-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181115_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.CharField(max_length=10, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='the_weather',
            field=models.CharField(max_length=10, verbose_name='气候'),
        ),
    ]
