# Generated by Django 2.0 on 2018-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20181115_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='today_or_future',
            field=models.IntegerField(default=1, verbose_name='天气日期类型'),
        ),
    ]
