# Generated by Django 2.0 on 2018-11-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_today_or_future'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-currentCity'], 'verbose_name': '天气', 'verbose_name_plural': '天气'},
        ),
    ]
