# Generated by Django 2.0 on 2018-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20181115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='温度'),
        ),
    ]
