# Generated by Django 2.0 on 2018-11-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_weather_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['currentCity'], 'verbose_name': '天气', 'verbose_name_plural': '天气'},
        ),
    ]
