# Generated by Django 2.0 on 2018-10-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_auto_20180912_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='content',
        ),
    ]
