# Generated by Django 2.0 on 2018-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_auto_20181010_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
