# Generated by Django 2.0 on 2018-10-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_auto_20181016_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='content',
        ),
    ]
