# Generated by Django 2.0 on 2018-10-16 04:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_remove_blog1_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0),
        ),
    ]
