# Generated by Django 2.0 on 2018-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0011_auto_20181018_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
