# Generated by Django 2.0 on 2018-11-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181104_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_time',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
