# Generated by Django 2.0 on 2018-11-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181009_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_account', models.CharField(max_length=20)),
                ('blog_password', models.CharField(max_length=20)),
                ('blog_username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_username', models.CharField(max_length=20)),
                ('blog_link', models.CharField(max_length=20)),
            ],
        ),
    ]
