# Generated by Django 2.0 on 2018-10-31 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_startistics', '0002_readnumdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
