# Generated by Django 2.0 on 2018-10-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_startistics', '0003_auto_20181031_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnumdate',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ReadNumDate',
        ),
    ]
