# Generated by Django 2.0 on 2018-11-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_startistics', '0005_readnumdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '具体哪一篇的阅读数量', 'verbose_name_plural': '具体哪一篇的阅读数量'},
        ),
        migrations.AlterModelOptions(
            name='readnumdate',
            options={'verbose_name': '热门阅读', 'verbose_name_plural': '热门阅读'},
        ),
    ]
