# Generated by Django 2.0 on 2018-11-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181103_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '微读书', 'verbose_name_plural': '微读书'},
        ),
    ]
