# Generated by Django 2.0 on 2018-11-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20181026_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reader_num',
        ),
    ]
